# Generated by Django 3.0.6 on 2020-05-12 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('test_type', models.CharField(choices=[('test', '考试'), ('debate', '答辩')], default='test', max_length=30)),
                ('lesson_status', models.CharField(choices=[('valid', '开课'), ('invalid', '未开课')], default='invalid', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('principal', models.CharField(max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='myClass',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('head_teacher', models.CharField(max_length=30)),
                ('grade', models.DateField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('IDCard', '身份证'), ('Passport', '护照')], default='IDCard', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('family_address', models.CharField(blank=True, max_length=30)),
                ('family_postcode', models.CharField(blank=True, max_length=30)),
                ('family_telephone', models.CharField(blank=True, max_length=30)),
                ('entry_date', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('myClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.myClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('IDCard', '身份证'), ('Passport', '护照')], default='IDCard', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('family_address', models.CharField(blank=True, max_length=30)),
                ('family_postcode', models.CharField(blank=True, max_length=30)),
                ('family_telephone', models.CharField(blank=True, max_length=30)),
                ('entry_date', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('teacher_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(choices=[('professor', '教授'), ('associate_professor', '副教授')], max_length=30)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Major')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('begin_semester', models.CharField(choices=[('spring', '春季学期'), ('autumn', '秋季学期')], max_length=30)),
                ('begin_time', models.IntegerField(choices=[(11, 'Monday1'), (12, 'Monday2'), (13, 'Monday3'), (14, 'Monday4'), (15, 'Monday5'), (16, 'Monday6'), (17, 'Monday7'), (18, 'Monday8'), (19, 'Monday9'), (21, 'Tuesday1'), (22, 'Tuesday2'), (23, 'Tuesday3'), (24, 'Tuesday4'), (25, 'Tuesday5'), (26, 'Tuesday6'), (27, 'Tuesday7'), (28, 'Tuesday8'), (29, 'Tuesday9'), (31, 'Wednesday1'), (32, 'Wednesday2'), (33, 'Wednesday3'), (34, 'Wednesday4'), (35, 'Wednesday5'), (36, 'Wednesday6'), (37, 'Wednesday7'), (38, 'Wednesday8'), (39, 'Wednesday9'), (41, 'Thursday1'), (42, 'Thursday2'), (43, 'Thursday3'), (44, 'Thursday4'), (45, 'Thursday5'), (46, 'Thursday6'), (47, 'Thursday7'), (48, 'Thursday8'), (49, 'Thursday9'), (51, 'Friday1'), (52, 'Friday2'), (53, 'Friday3'), (54, 'Friday4'), (55, 'Friday5'), (56, 'Friday6'), (57, 'Friday7'), (58, 'Friday8'), (59, 'Friday9')])),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valid_status', to='manager.Lesson')),
                ('students', models.ManyToManyField(related_name='students', through='manager.LessonSelect', to='manager.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MajorTransfer',
            fields=[
                ('chenge_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('change_date', models.DateField()),
                ('has_transfered_communist_youth_league_relationship', models.BooleanField(default=False)),
                ('current_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='major_current_class', to='manager.myClass')),
                ('original_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='major_original_class', to='manager.myClass')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='major_transfer', to='manager.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lessonselect',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Student'),
        ),
        migrations.AddField(
            model_name='lessonselect',
            name='valid_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ValidLesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Major'),
        ),
        migrations.CreateModel(
            name='GradeTransfer',
            fields=[
                ('chenge_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('change_date', models.DateField()),
                ('degrade_reason', models.CharField(choices=[('suspension', '休学'), ('volunteer_teaching', '支教')], max_length=30)),
                ('current_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degrade_current_class', to='manager.myClass')),
                ('original_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degrade_original_class', to='manager.myClass')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_transfer', to='manager.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
