# Generated by Django 3.0.4 on 2020-05-20 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=256),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123456', max_length=256),
        ),
        migrations.AlterField(
            model_name='gradetransfer',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_current_class', to='manager.myClass'),
        ),
        migrations.AlterField(
            model_name='gradetransfer',
            name='original_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_original_class', to='manager.myClass'),
        ),
        migrations.AlterField(
            model_name='majortransfer',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_current_class', to='manager.myClass'),
        ),
        migrations.AlterField(
            model_name='majortransfer',
            name='original_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_original_class', to='manager.myClass'),
        ),
    ]
