# Generated by Django 3.0.6 on 2020-05-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200522_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson', to='manager.Major'),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myClass', to='manager.Major'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='manager.Major'),
        ),
    ]
