# Generated by Django 3.0.4 on 2020-05-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200522_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='manager.Major'),
        ),
        migrations.AlterField(
            model_name='lessonselect',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SelectLesson', to='manager.Student'),
        ),
        migrations.AlterField(
            model_name='lessonselect',
            name='valid_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BeSelected', to='manager.ValidLesson'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='manager.Major'),
        ),
    ]
