# Generated by Django 3.0.4 on 2020-05-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200522_2051'),
        ('manager', '0005_auto_20200522_2056'),
    ]

    operations = [
    ]
