# Generated by Django 3.0.4 on 2020-05-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_merge_20200522_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradetransfer',
            old_name='chenge_id',
            new_name='change_id',
        ),
        migrations.RenameField(
            model_name='majortransfer',
            old_name='chenge_id',
            new_name='change_id',
        ),
        migrations.AlterField(
            model_name='myclass',
            name='head_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HostClass', to='manager.Teacher'),
        ),
    ]
