# Generated by Django 3.0.4 on 2020-05-23 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20200523_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonselect',
            name='score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
